export const commonActionTypes = {
    SET_SITE_LOGO : 'SET_SITE_LOGO',
    SET_COPYRIGHTS : 'SET_COPYRIGHTS',
    SET_FOOTER_ABOUT : 'SET_FOOTER_ABOUT',
    SET_TALK_TO_US : 'SET_TALK_TO_US',
    SET_SOCIAL_MEDIA : 'SET_SOCIAL_MEDIA',
    SET_ALL_STREAMS : 'SET_ALL_STREAMS',
    SET_ALL_LOCATIONS : 'SET_ALL_LOCATIONS',
    SET_SEARCH_BANNER : 'SET_SEARCH_BANNER',
    SET_CLASS_CATEGORIES : 'SET_CLASS_CATEGORIES',
    SET_CLASS_CAPACITIES : 'SET_CLASS_CAPACITIES',
    SET_INSTITUTE_LIST : 'SET_INSTITUTE_LIST',
}