export const homeActionTypes = {
    SET_HOME_PAGE_BANNER : 'SET_HOME_PAGE_BANNER',
    SET_WELCOME_TEXT : 'SET_WELCOME_TEXT',
    SET_SERVICES : 'SET_SERVICES',
    SET_COUNTER_BG : 'SET_COUNTER_BG',
    SET_FEATURES : 'SET_FEATURES',
    SET_TESTIMONIALS : 'SET_TESTIMONIALS',
    SET_NEWEST_GURUS : 'SET_NEWEST_GURUS',
    SET_GURUS_COUNT : 'SET_GURUS_COUNT',
    SET_TOTAL_CLASSES : 'SET_TOTAL_CLASSES',
    SET_TOTAL_VIDEOS : 'SET_TOTAL_VIDEOS'
}